version: '1'
services:
  mongodb:
    build: ./Mongodb
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./Mongodb/data:/data/db
    env_file: 
      - .env
    command: [--auth]
    restart: always